### PR TITLE
Add next tag to tekton on-push

### PR DESCRIPTION
**Pull request by michael-valdron**
# Description of Changes
_Summarize the changes you made as part of this pull request._

Adds `next` as an additional tag to the on-push tekton task.

# Related Issue(s)
_Link the GitHub/GitLab/JIRA issues that are related to this PR._

Part of https://github.com/devfile/api/issues/1657

# Acceptance Criteria

- [x] Unit Tests
- [x] E2E Tests
- [ ] Documentation
_Update the [sidebar](https://github.com/devfile/devfile-web/tree/main/apps/landing-page#configuring-navigation) if there is a new file added or an existing filename is changed_

# Tests Performed
_Explain what tests you personally ran to ensure the changes are functioning as expected._

# How To Test
_Instructions for the reviewer on how to test your changes._

# Notes To Reviewer
_Any notes you would like to include for the reviewer._

### CODE REVIEW

**Comment by michael-valdron** [comment]
> Documentation
> Update the [sidebar](https://github.com/devfile/devfile-web/tree/main/apps/landing-page#configuring-navigation) if there is a new file added or an existing filename is changed

N/A

**Review by Jdubrick — APPROVED** [review]
lgtm

**Comment by michael-valdron** [comment]
/hold

Waiting on merging https://github.com/devfile/registry/pull/529 first.

**Pull request merged**
