### PR TITLE
Landing Page - Updates to Introduction Section #925

### PR DESCRIPTION
**Pull request by callmetushar123**
Signed-off-by: Tushar <tusharbarman123@gmail.com>

**What does this PR do / why we need it**:
I have updated the "What is devfile " section as requested in the issue #925
**Which issue(s) this PR fixes**:

Fixes #925?

**PR acceptance criteria**:

- [ ] Unit Tests
- [ ] E2E Tests
- [ ] Documentation

**How to test changes / Special notes to the reviewer**:

### CODE REVIEW

**Comment by callmetushar123** [comment]
@kim-tsao Made the appropriate changes

**Comment by callmetushar123** [comment]
@schultzp2020 please review the changes

**Comment by callmetushar123** [comment]
@elsony can you please review the changes?

**Review by elsony — APPROVED** [review]
/lgtm

**Comment by callmetushar123** [comment]
@elsony why is it not completing the test cases?

**Pull request merged**
