### PR TITLE
Amazon CodeCatalyst supports devfile

### PR DESCRIPTION
**Pull request by mayilian**
Adding `Amazon CodeCatalyst Dev Environments` to the list of tools that provide devfile support

## What does this PR do / why we need it

Enhancing the documentation to mention `Amazon CodeCatalyst Dev Environments` in the tools supporting devfile

## Which issue(s) does this PR fix

Fixes #?

## PR acceptance criteria

- [ ] Unit Tests
- [ ] E2E Tests
- [x] Documentation

### CODE REVIEW

**Review by elsony — APPROVED** [review]
/lgtm

**Comment by elsony** [comment]
Please sign off this commit (see DCO check above for details).

**Comment by mayilian** [comment]
> Please sign off this commit (see DCO check above for details).

Added in the extended commit message, will this be enough? At this moment I don't have the local copy.

**Comment by mayilian** [comment]
Ok, did as recommended

**Review by elsony — APPROVED** [review]
/lgtm

**Comment by elsony** [comment]
Changes went live

**Comment by mayilian** [comment]
Thanks!

**Pull request merged**
