### PR TITLE
[Devtools week] Update license headers

### PR DESCRIPTION
**Pull request by thepetk**
## What does this PR do / why we need it
Updates the license header copyrights line to `Copyright Red Hat`

## Which issue(s) does this PR fix
Fixes https://github.com/devfile/api/issues/1241

## PR acceptance criteria

- [x] Unit Tests
- [x] E2E Tests
- [x] Documentation
_Update the [sidebar](https://github.com/devfile/devfile-web/tree/main/apps/landing-page#configuring-navigation) if there is a new file added or an existing filename is changed_

### CODE REVIEW

**Review by rm3l — COMMENTED** [review]
Maybe I missed something, but I thought this would be more about updating the headers in **all** source files (code, scripts, in-tree doc files, but excluding generated ones) once and for all, no?

**Comment by thepetk** [comment]
> Maybe I missed something, but I thought this would be more about updating the headers in **all** source files (code, scripts, in-tree doc files, but excluding generated ones) once and for all, no?

I've only updated this file as it is explicitly mentioned in the linked issue:
"A process would run an update on the year entry under the [devfile-web license header file](https://github.com/devfile/devfile-web/blob/4286b77fec024f4783b464e5a4a333b3989e244c/license-header.js) annually at the start of the new year to remove the need to do this manually on a yearly basis."

**Review by rm3l — APPROVED** [review]
> > Maybe I missed something, but I thought this would be more about updating the headers in **all** source files (code, scripts, in-tree doc files, but excluding generated ones) once and for all, no?
> 
> I've only updated this file as it is explicitly mentioned in the linked issue: "A process would run an update on the year entry under the [devfile-web license header file](https://github.com/devfile/devfile-web/blob/4286b77fec024f4783b464e5a4a333b3989e244c/license-header.js) annually at the start of the new year to remove the need to do this manually on a yearly basis."

Oh fine then - thanks. I thought it was just any source file being updated, but I can see that this file is actually used (enforced?) by an ESLint plugin: https://github.com/devfile/devfile-web/blob/main/.eslintrc.json#L102

**Review by michael-valdron — COMMENTED** [review]
> > > Maybe I missed something, but I thought this would be more about updating the headers in **all** source files (code, scripts, in-tree doc files, but excluding generated ones) once and for all, no?
> > 
> > 
> > I've only updated this file as it is explicitly mentioned in the linked issue: "A process would run an update on the year entry under the [devfile-web license header file](https://github.com/devfile/devfile-web/blob/4286b77fec024f4783b464e5a4a333b3989e244c/license-header.js) annually at the start of the new year to remove the need to do this manually on a yearly basis."
> 
> Oh fine then - thanks. I thought it was just any source file being updated, but I can see that this file is actually used (enforced?) by an ESLint plugin: https://github.com/devfile/devfile-web/blob/main/.eslintrc.json#L102

~Might be best to update the source headers too in this case.~ See https://github.com/devfile/devfile-web/pull/95#issuecomment-1720228959

Job seems to be ok with current changes: https://github.com/devfile/devfile-web/actions/runs/6185032661/job/16789828817?pr=95

But when I run `yarn nx affected --target=lint --parallel=3` locally it fails:
```
$ /home/mvaldron/source/repos/thepetk/devfile-web/node_modules/.bin/nx affected --target=lint --parallel=3

 >  NX   workspace.json is ignored

   Nx no longer reads configuration from workspace.json.
   Run "nx g @nrwl/workspace:fix-configuration" to split workspace.json into individual project.json files.


 >  NX   Affected criteria defaulted to --base=main --head=HEAD



    ✖  nx run landing-page:lint
       Linting "landing-page"...
       Browserslist: caniuse-lite is outdated. Please run:
         npx browserslist@latest --update-db
         Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating
       
       /home/mvaldron/source/repos/thepetk/devfile-web/apps/landing-page/index.d.ts
         1:1  error  Invalid license header  license-header/header
       
       /home/mvaldron/source/repos/thepetk/devfile-web/apps/landing-page/jest.config.ts
         1:1  error  Invalid license header  license-header/header
       
       /home/mvaldron/source/repos/thepetk/devfile-web/apps/landing-page/markdoc/nodes.tsx
         1:1  error  Invalid license header  license-header/header
       
       /home/mvaldron/source/repos/thepetk/devfile-web/apps/landing-page/markdoc/tags.tsx
         1:1  error  Invalid license header  license-header/header
       
       /home/mvaldron/source/repos/thepetk/devfile-web/apps/landing-page/navigation.ts
         1:1  error  Invalid license header  license-header/header
       
       /home/mvaldron/source/repos/thepetk/devfile-web/apps/landing-page/next.config.js
         1:1  error  Invalid license header  license-header/header
       
       /home/mvaldron/source/repos/thepetk/devfile-web/apps/landing-page/pages/404.tsx
         1:1  error  Invalid license header  license-header/header
       
       /home/mvaldron/source/repos/thepetk/devfile-web/apps/landing-page/pages/_app.tsx
         1:1  error  Invalid license header  license-header/header
       
       /home/mvaldron/source/repos/thepetk/devfile-web/apps/landing-page/pages/_document.tsx
         1:1  error  Invalid license header  license-header/header
       
       /home/mvaldron/source/repos/thepetk/devfile-web/apps/landing-page/pages/index.tsx
         1:1  error  Invalid license header  license-header/header
       
       /home/mvaldron/source/repos/thepetk/devfile-web/apps/landing-page/postcss.config.js
         1:1  error  Invalid license header  license-header/header
       
       /home/mvaldron/source/repos/thepetk/devfile-web/apps/landing-page/tailwind.config.js
         1:1  error  Invalid license header  license-header/header
       
       ✖ 12 problems (12 errors, 0 warnings)
         12 errors and 0 warnings potentially fixable with the `--fix` option.
       
       Lint errors found in the listed files.
       

    ✖  nx run registry-viewer:lint
       Linting "registry-viewer"...
       
       /home/mvaldron/source/repos/thepetk/devfile-web/apps/registry-viewer/config.ts
         1:1  error  Invalid license header  license-header/header
       
       /home/mvaldron/source/repos/thepetk/devfile-web/apps/registry-viewer/index.d.ts
         1:1  error  Invalid license header  license-header/header
       
       /home/mvaldron/source/repos/thepetk/devfile-web/apps/registry-viewer/jest.config.ts
         1:1  error  Invalid license header  license-header/header
       
       /home/mvaldron/source/repos/thepetk/devfile-web/apps/registry-viewer/navigation.ts
         1:1  error  Invalid license header  license-header/header
       
       /home/mvaldron/source/repos/thepetk/devfile-web/apps/registry-viewer/next.config.js
         1:1  error  Invalid license header  license-header/header
       
       /home/mvaldron/source/repos/thepetk/devfile-web/apps/registry-viewer/pages/404.tsx
         1:1  error  Invalid license header  license-header/header
       
       /home/mvaldron/source/repos/thepetk/devfile-web/apps/registry-viewer/pages/_app.tsx
         1:1  error  Invalid license header  license-header/header
       
       /home/mvaldron/source/repos/thepetk/devfile-web/apps/registry-viewer/pages/_document.tsx
         1:1  error  Invalid license header  license-header/header
       
       /home/mvaldron/source/repos/thepetk/devfile-web/apps/registry-viewer/pages/devfiles/[devfile-registry]/[devfile]/index.tsx
         1:1  error  Invalid license header  license-header/header
       
       /home/mvaldron/source/repos/thepetk/devfile-web/apps/registry-viewer/pages/devfiles/[devfile-registry]/index.tsx
         1:1  error  Invalid license header  license-header/header
       
       /home/mvaldron/source/repos/thepetk/devfile-web/apps/registry-viewer/pages/index.tsx
         1:1  error  Invalid license header  license-header/header
       
       /home/mvaldron/source/repos/thepetk/devfile-web/apps/registry-viewer/postcss.config.js
         1:1  error  Invalid license header  license-header/header
       
       /home/mvaldron/source/repos/thepetk/devfile-web/apps/registry-viewer/tailwind.config.js
         1:1  error  Invalid license header  license-header/header
       
       ✖ 13 problems (13 errors, 0 warnings)
         13 errors and 0 warnings potentially fixable with the `--fix` option.
       
       Lint errors found in the listed files.
       

    ✖  nx run core:lint
       Linting "core"...
       
       /home/mvaldron/source/repos/thepetk/devfile-web/libs/core/jest.config.ts
         1:1  error  Invalid license header  license-header/header
       
       /home/mvaldron/source/repos/thepetk/devfile-web/libs/core/src/components/button/button.tsx
         1:1  error  Invalid license header  license-header/header
       
       /home/mvaldron/source/repos/thepetk/devfile-web/libs/core/src/components/callout/callout.tsx
         1:1  error  Invalid license header  license-header/header
       
       /home/mvaldron/source/repos/thepetk/devfile-web/libs/core/src/components/cncf-banner/cncf-banner.tsx
         1:1  error  Invalid license header  license-header/header
       
       /home/mvaldron/source/repos/thepetk/devfile-web/libs/core/src/components/current-version/current-version.tsx
         1:1  error  Invalid license header  license-header/header
       
       /home/mvaldron/source/repos/thepetk/devfile-web/libs/core/src/components/custom-404/custom-404.tsx
         1:1  error  Invalid license header  license-header/header
       
       /home/mvaldron/source/repos/thepetk/devfile-web/libs/core/src/components/devfile-codeblock/devfile-codeblock.tsx
         1:1  error  Invalid license header  license-header/header
       
       /home/mvaldron/source/repos/thepetk/devfile-web/libs/core/src/components/devfile-datalist/devfile-datalist.tsx
         1:1  error  Invalid license header  license-header/header
       
       /home/mvaldron/source/repos/thepetk/devfile-web/libs/core/src/components/devfile-filters/devfile-filter.tsx
         1:1  error  Invalid license header  license-header/header
       
       /home/mvaldron/source/repos/thepetk/devfile-web/libs/core/src/components/devfile-filters/devfile-filters.tsx
         1:1  error  Invalid license header  license-header/header
       
       /home/mvaldron/source/repos/thepetk/devfile-web/libs/core/src/components/devfile-grid/devfile-grid.tsx
         1:1  error  Invalid license header  license-header/header
       
       /home/mvaldron/source/repos/thepetk/devfile-web/libs/core/src/components/devfile-header/devfile-header.tsx
         1:1  error  Invalid license header  license-header/header
       
       /home/mvaldron/source/repos/thepetk/devfile-web/libs/core/src/components/devfile-search/devfile-search.tsx
         1:1  error  Invalid license header  license-header/header
       
       /home/mvaldron/source/repos/thepetk/devfile-web/libs/core/src/components/devfile-starter-projects/devfile-starter-projects.tsx
         1:1  error  Invalid license header  license-header/header
       
       /home/mvaldron/source/repos/thepetk/devfile-web/libs/core/src/components/fence/fence.tsx
         1:1  error  Invalid license header  license-header/header
       
       /home/mvaldron/source/repos/thepetk/devfile-web/libs/core/src/components/footer/footer.tsx
         1:1  error  Invalid license header  license-header/header
       
       /home/mvaldron/source/repos/thepetk/devfile-web/libs/core/src/components/header/header-breadcrumbs.tsx
         1:1  error  Invalid license header  license-header/header
       
       /home/mvaldron/source/repos/thepetk/devfile-web/libs/core/src/components/header/header.tsx
         1:1  error  Invalid license header  license-header/header
       
       /home/mvaldron/source/repos/thepetk/devfile-web/libs/core/src/components/hero-background/hero-background.tsx
         1:1  error  Invalid license header  license-header/header
       
       /home/mvaldron/source/repos/thepetk/devfile-web/libs/core/src/components/hero/hero.tsx
         1:1  error  Invalid license header  license-header/header
       
       /home/mvaldron/source/repos/thepetk/devfile-web/libs/core/src/components/icon/icon.tsx
         1:1  error  Invalid license header  license-header/header
       
       /home/mvaldron/source/repos/thepetk/devfile-web/libs/core/src/components/index.ts
         1:1  error  Invalid license header  license-header/header
       
       /home/mvaldron/source/repos/thepetk/devfile-web/libs/core/src/components/json-schema-viewer/json-schema-viewer-description.tsx
         1:1  error  Invalid license header  license-header/header
       
       /home/mvaldron/source/repos/thepetk/devfile-web/libs/core/src/components/json-schema-viewer/json-schema-viewer-dropdown.tsx
         1:1  error  Invalid license header  license-header/header
       
       /home/mvaldron/source/repos/thepetk/devfile-web/libs/core/src/components/json-schema-viewer/json-schema-viewer-element.tsx
         1:1  error  Invalid license header  license-header/header
       
       /home/mvaldron/source/repos/thepetk/devfile-web/libs/core/src/components/json-schema-viewer/json-schema-viewer-panel.tsx
         1:1  error  Invalid license header  license-header/header
       
       /home/mvaldron/source/repos/thepetk/devfile-web/libs/core/src/components/json-schema-viewer/json-schema-viewer-tags.tsx
         1:1  error  Invalid license header  license-header/header
       
       /home/mvaldron/source/repos/thepetk/devfile-web/libs/core/src/components/json-schema-viewer/json-schema-viewer.tsx
         1:1  error  Invalid license header  license-header/header
       
       /home/mvaldron/source/repos/thepetk/devfile-web/libs/core/src/components/key-features-section/key-features-section.tsx
         1:1  error  Invalid license header  license-header/header
       
       /home/mvaldron/source/repos/thepetk/devfile-web/libs/core/src/components/landing-page-search/landing-page-search.tsx
         1:1  error  Invalid license header  license-header/header
       
       /home/mvaldron/source/repos/thepetk/devfile-web/libs/core/src/components/meta/landing-page-meta.tsx
         1:1  error  Invalid license header  license-header/header
       
       /home/mvaldron/source/repos/thepetk/devfile-web/libs/core/src/components/meta/meta.tsx
         1:1  error  Invalid license header  license-header/header
       
       /home/mvaldron/source/repos/thepetk/devfile-web/libs/core/src/components/meta/registry-meta.tsx
         1:1  error  Invalid license header  license-header/header
       
       /home/mvaldron/source/repos/thepetk/devfile-web/libs/core/src/components/mobile-navigation/mobile-navigation.tsx
         1:1  error  Invalid license header  license-header/header
       
       /home/mvaldron/source/repos/thepetk/devfile-web/libs/core/src/components/navigation/navigation.tsx
         1:1  error  Invalid license header  license-header/header
       
       /home/mvaldron/source/repos/thepetk/devfile-web/libs/core/src/components/pagination/pagination.tsx
         1:1  error  Invalid license header  license-header/header
       
       /home/mvaldron/source/repos/thepetk/devfile-web/libs/core/src/components/prose/prose.tsx
         1:1  error  Invalid license header  license-header/header
       
       /home/mvaldron/source/repos/thepetk/devfile-web/libs/core/src/components/quick-links/quick-links.tsx
         1:1  error  Invalid license header  license-header/header
       
       /home/mvaldron/source/repos/thepetk/devfile-web/libs/core/src/components/theme-selector/theme-selector.tsx
         1:1  error  Invalid license header  license-header/header
       
       /home/mvaldron/source/repos/thepetk/devfile-web/libs/core/src/components/value-proposition-section/value-proposition-section.tsx
         1:1  error  Invalid license header  license-header/header
       
       /home/mvaldron/source/repos/thepetk/devfile-web/libs/core/src/components/version-selector/version-selector.tsx
         1:1  error  Invalid license header  license-header/header
       
       /home/mvaldron/source/repos/thepetk/devfile-web/libs/core/src/components/video/video.tsx
         1:1  error  Invalid license header  license-header/header
       
       /home/mvaldron/source/repos/thepetk/devfile-web/libs/core/src/functions/compare-semantic-versions/compare-semantic-versions.spec.tsx
         1:1  error  Invalid license header  license-header/header
       
       /home/mvaldron/source/repos/thepetk/devfile-web/libs/core/src/functions/compare-semantic-versions/compare-semantic-versions.tsx
         1:1  error  Invalid license header  license-header/header
       
       /home/mvaldron/source/repos/thepetk/devfile-web/libs/core/src/functions/fetch-devfiles/fetch-devfiles.spec.tsx
         1:1  error  Invalid license header  license-header/header
       
       /home/mvaldron/source/repos/thepetk/devfile-web/libs/core/src/functions/fetch-devfiles/fetch-devfiles.tsx
         1:1  error  Invalid license header  license-header/header
       
       /home/mvaldron/source/repos/thepetk/devfile-web/libs/core/src/functions/get-user-region/get-user-region.spec.tsx
         1:1  error  Invalid license header  license-header/header
       
       /home/mvaldron/source/repos/thepetk/devfile-web/libs/core/src/functions/get-user-region/get-user-region.tsx
         1:1  error  Invalid license header  license-header/header
       
       /home/mvaldron/source/repos/thepetk/devfile-web/libs/core/src/functions/index.ts
         1:1  error  Invalid license header  license-header/header
       
       /home/mvaldron/source/repos/thepetk/devfile-web/libs/core/src/hooks/index.ts
         1:1  error  Invalid license header  license-header/header
       
       /home/mvaldron/source/repos/thepetk/devfile-web/libs/core/src/hooks/use-analytics/use-analytics.tsx
         1:1  error  Invalid license header  license-header/header
       
       /home/mvaldron/source/repos/thepetk/devfile-web/libs/core/src/hooks/use-codeblock/use-codeblock.tsx
         1:1  error  Invalid license header  license-header/header
       
       /home/mvaldron/source/repos/thepetk/devfile-web/libs/core/src/hooks/use-fast-context/use-fast-context.tsx
         1:1  error  Invalid license header  license-header/header
       
       /home/mvaldron/source/repos/thepetk/devfile-web/libs/core/src/hooks/use-links/use-links.tsx
         1:1  error  Invalid license header  license-header/header
       
       /home/mvaldron/source/repos/thepetk/devfile-web/libs/core/src/hooks/use-navigation/use-navigation.tsx
         1:1  error  Invalid license header  license-header/header
       
       /home/mvaldron/source/repos/thepetk/devfile-web/libs/core/src/hooks/use-table-of-contents/use-table-of-contents.tsx
         1:1  error  Invalid license header  license-header/header
       
       /home/mvaldron/source/repos/thepetk/devfile-web/libs/core/src/icons/amazon-web-services-icon.tsx
         1:1  error  Invalid license header  license-header/header
       
       /home/mvaldron/source/repos/thepetk/devfile-web/libs/core/src/icons/devfile-icon.tsx
         1:1  error  Invalid license header  license-header/header
       
       /home/mvaldron/source/repos/thepetk/devfile-web/libs/core/src/icons/github-icon.tsx
         1:1  error  Invalid license header  license-header/header
       
       /home/mvaldron/source/repos/thepetk/devfile-web/libs/core/src/icons/ibm-icon.tsx
         1:1  error  Invalid license header  license-header/header
       
       /home/mvaldron/source/repos/thepetk/devfile-web/libs/core/src/icons/index.ts
         1:1  error  Invalid license header  license-header/header
       
       /home/mvaldron/source/repos/thepetk/devfile-web/libs/core/src/icons/installation-icon.tsx
         1:1  error  Invalid license header  license-header/header
       
       /home/mvaldron/source/repos/thepetk/devfile-web/libs/core/src/icons/jetbrains-icon.tsx
         1:1  error  Invalid license header  license-header/header
       
       /home/mvaldron/source/repos/thepetk/devfile-web/libs/core/src/icons/lightbulb-icon.tsx
         1:1  error  Invalid license header  license-header/header
       
       /home/mvaldron/source/repos/thepetk/devfile-web/libs/core/src/icons/plugins-icon.tsx
         1:1  error  Invalid license header  license-header/header
       
       /home/mvaldron/source/repos/thepetk/devfile-web/libs/core/src/icons/presets-icon.tsx
         1:1  error  Invalid license header  license-header/header
       
       /home/mvaldron/source/repos/thepetk/devfile-web/libs/core/src/icons/red-hat-icon.tsx
         1:1  error  Invalid license header  license-header/header
       
       /home/mvaldron/source/repos/thepetk/devfile-web/libs/core/src/icons/slack-icon.tsx
         1:1  error  Invalid license header  license-header/header
       
       /home/mvaldron/source/repos/thepetk/devfile-web/libs/core/src/icons/theming-icon.tsx
         1:1  error  Invalid license header  license-header/header
       
       /home/mvaldron/source/repos/thepetk/devfile-web/libs/core/src/icons/warning-icon.tsx
         1:1  error  Invalid license header  license-header/header
       
       /home/mvaldron/source/repos/thepetk/devfile-web/libs/core/src/index.ts
         1:1  error  Invalid license header  license-header/header
       
       /home/mvaldron/source/repos/thepetk/devfile-web/libs/core/src/layouts/index.ts
         1:1  error  Invalid license header  license-header/header
       
       /home/mvaldron/source/repos/thepetk/devfile-web/libs/core/src/layouts/landing-page-layout/landing-page-layout.tsx
         1:1  error  Invalid license header  license-header/header
       
       /home/mvaldron/source/repos/thepetk/devfile-web/libs/core/src/types/custom-404.ts
         1:1  error  Invalid license header  license-header/header
       
       /home/mvaldron/source/repos/thepetk/devfile-web/libs/core/src/types/index.ts
         1:1  error  Invalid license header  license-header/header
       
       ✖ 75 problems (75 errors, 0 warnings)
         75 errors and 0 warnings potentially fixable with the `--fix` option.
       
       Lint errors found in the listed files.
       

    ✖  nx run registry-viewer-e2e:lint
       Linting "registry-viewer-e2e"...
       
       /home/mvaldron/source/repos/thepetk/devfile-web/apps/registry-viewer-e2e/cypress.config.ts
         1:1  error  Invalid license header  license-header/header
       
       /home/mvaldron/source/repos/thepetk/devfile-web/apps/registry-viewer-e2e/src/e2e/app.cy.ts
         1:1  error  Invalid license header  license-header/header
       
       /home/mvaldron/source/repos/thepetk/devfile-web/apps/registry-viewer-e2e/src/support/app.po.ts
         1:1  error  Invalid license header  license-header/header
       
       /home/mvaldron/source/repos/thepetk/devfile-web/apps/registry-viewer-e2e/src/support/commands.ts
         1:1  error  Invalid license header  license-header/header
       
       /home/mvaldron/source/repos/thepetk/devfile-web/apps/registry-viewer-e2e/src/support/e2e.ts
         1:1  error  Invalid license header  license-header/header
       
       ✖ 5 problems (5 errors, 0 warnings)
         5 errors and 0 warnings potentially fixable with the `--fix` option.
       
       Lint errors found in the listed files.
       

    ✖  nx run landing-page-e2e:lint
       Linting "landing-page-e2e"...
       
       /home/mvaldron/source/repos/thepetk/devfile-web/apps/landing-page-e2e/cypress.config.ts
         1:1  error  Invalid license header  license-header/header
       
       /home/mvaldron/source/repos/thepetk/devfile-web/apps/landing-page-e2e/src/e2e/app.cy.ts
         1:1  error  Invalid license header  license-header/header
       
       /home/mvaldron/source/repos/thepetk/devfile-web/apps/landing-page-e2e/src/support/commands.ts
         1:1  error  Invalid license header  license-header/header
       
       /home/mvaldron/source/repos/thepetk/devfile-web/apps/landing-page-e2e/src/support/e2e.ts
         1:1  error  Invalid license header  license-header/header
       
       ✖ 4 problems (4 errors, 0 warnings)
         4 errors and 0 warnings potentially fixable with the `--fix` option.
       
       Lint errors found in the listed files.
       

 ————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

 >  NX   Ran target lint for 5 projects (15s)
 
    ✔    0/5 succeeded [0 read from cache]
 
    ✖    5/5 targets failed, including the following:
         - nx run landing-page:lint
         - nx run registry-viewer:lint
         - nx run core:lint
         - nx run registry-viewer-e2e:lint
         - nx run landing-page-e2e:lint
 
   View structured, searchable error logs at https://nx.app/runs/49nE35FC1j

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by michael-valdron** [comment]
> https://github.com/devfile/devfile-web/pull/95#pullrequestreview-1627820072

Passing linter on the workflow might be a bug.

**Comment by michael-valdron** [comment]
> https://github.com/devfile/devfile-web/pull/95#pullrequestreview-1627820072

It's passing on the workflow because it only errors if files are changed, this may work for us as this is the process we typically do when the header file is changed.

**Comment by rm3l** [comment]
> Might be best to update the source headers too in this case. See https://github.com/devfile/devfile-web/pull/95#issuecomment-1720228959
>
> Job seems to be ok with current changes: [devfile/devfile-web/actions/runs/6185032661/job/16789828817?pr=95](https://github.com/devfile/devfile-web/actions/runs/6185032661/job/16789828817?pr=95)
>
> But when I run yarn nx affected --target=lint --parallel=3 locally it fails:

This is weird. I ran the same command locally yesterday, and it worked. That's why I was confused as to whether the linter was enforcing the headers in the sources.

```
☸ k3d-local-k8s-cluster (default) in ~/w/p/d/devfile-web on  ft/update_license_headers [$?] via  v18.16.1 took 2s 
$ yarn nx affected --target=lint --parallel=3
yarn run v1.22.19
$ /home/asoro/work/projects/devfile/devfile-web/node_modules/.bin/nx affected --target=lint --parallel=3

 >  NX   workspace.json is ignored

   Nx no longer reads configuration from workspace.json.
   Run "nx g @nrwl/workspace:fix-configuration" to split workspace.json into individual project.json files.


 >  NX   Affected criteria defaulted to --base=main --head=HEAD

 >  NX   Successfully ran target lint for 0 projects (5ms)
 
   View logs and run details at https://nx.app/runs/q9GzBxOjbO

Done in 0.43s.

☸ k3d-local-k8s-cluster (default) in ~/w/p/d/devfile-web on  ft/update_license_headers [$?] via  v18.16.1 
$ echo $?                                                             
0
```

> > [#95 (review)](https://github.com/devfile/devfile-web/pull/95#pullrequestreview-1627820072)
> 
> It's passing on the workflow because it only errors if files are changed, this may work for us as this is the process we typically do when the header file is changed.

Ok, I think it should be fine then in this case. Next time a source is changed, people would need to update the corresponding header accordingly. Thanks @michael-valdron !

**Comment by thepetk** [comment]
> I ran the same command locally yesterday, and it worked. That's why I was confused as to whether the linter was enforcing the headers in the sources. But I see, it errors out only for changed files.

Plus one locally it works for me too. Let 


> > Might be best to update the source headers too in this case. See [#95 (comment)](https://github.com/devfile/devfile-web/pull/95#issuecomment-1720228959)
> > Job seems to be ok with current changes: [devfile/devfile-web/actions/runs/6185032661/job/16789828817?pr=95](https://github.com/devfile/devfile-web/actions/runs/6185032661/job/16789828817?pr=95)
> > But when I run yarn nx affected --target=lint --parallel=3 locally it fails:
> 
> I ran the same command locally yesterday, and it worked. That's why I was confused as to whether the linter was enforcing the headers in the sources. But I see, it errors out only for changed files.
> 
> ```
> ☸ k3d-local-k8s-cluster (default) in ~/w/p/d/devfile-web on  ft/update_license_headers [$?] via  v18.16.1 took 2s 
> $ yarn nx affected --target=lint --parallel=3
> yarn run v1.22.19
> $ /home/asoro/work/projects/devfile/devfile-web/node_modules/.bin/nx affected --target=lint --parallel=3
> 
>  >  NX   workspace.json is ignored
> 
>    Nx no longer reads configuration from workspace.json.
>    Run "nx g @nrwl/workspace:fix-configuration" to split workspace.json into individual project.json files.
> 
> 
>  >  NX   Affected criteria defaulted to --base=main --head=HEAD
> 
>  >  NX   Successfully ran target lint for 0 projects (5ms)
>  
>    View logs and run details at https://nx.app/runs/q9GzBxOjbO
> 
> Done in 0.43s.
> 
> ☸ k3d-local-k8s-cluster (default) in ~/w/p/d/devfile-web on  ft/update_license_headers [$?] via  v18.16.1 
> $ echo $?                                                             
> 0
> ```
> 
> > > [#95 (review)](https://github.com/devfile/devfile-web/pull/95#pullrequestreview-1627820072)
> > 
> > 
> > It's passing on the workflow because it only errors if files are changed, this may work for us as this is the process we typically do when the header file is changed.
> 
> Ok, I think it should be fine then in this case. Next time a source is changed, people would need to update the corresponding header accordingly. Thanks @michael-valdron !

IMO it would be better to update all source files now as people working on different topics might spend time to identify the issue etc. I've updated the PR accordingly :) Let me know WDYT

**Comment by rm3l** [comment]
> IMO it would be better to update all source files now as people working on different topics might spend time to identify the issue etc. I've updated the PR accordingly :) Let me know WDYT
> 

Sounds good too. Thanks!

**Review by rm3l — APPROVED** [review]
> IMO it would be better to update all source files now as people working on different topics might spend time to identify the issue etc. I've updated the PR accordingly :) Let me know WDYT
> 

Sounds good too. Thanks!

**Review by michael-valdron — APPROVED** [review]

**Review by michael-valdron — APPROVED** [review]
/lgtm

**Pull request merged**
