### PR TITLE
Update landing page and registry viewer to use Node.js 18 (latest LTS)

### PR DESCRIPTION
**Pull request by rm3l**
## What does this PR do / why we need it
This updates the landing page and registry viewer to use the latest LTS for Node.js, which is 18 at this time. See https://github.com/devfile/api/issues/1117 for more context.

It also makes sure the expected versions of Node and Yarn are consistently used when working with this repo.

## Which issue(s) does this PR fix
Fixes https://github.com/devfile/api/issues/1117

## PR acceptance criteria

- [ ] Unit Tests
- [ ] E2E Tests
- [ ] Documentation
_Update the [sidebar](https://github.com/devfile/devfile-web/tree/main/apps/landing-page#configuring-navigation) if there is a new file added or an existing filename is changed_

## How to test changes / Special notes to the reviewer
Not sure if there are any other files to change, so please do let me know.

### CODE REVIEW

**Review by thepetk — APPROVED** [review]
/lgtm as I've tested locally and it was ok.

**Comment by rm3l** [comment]
Had to rebase and force-push the branch to meet the requirement of having the branch up to date before merging. @thepetk Feel free to re-lgtm if it looks okay with you.

**Review by thepetk — APPROVED** [review]
/lgtm as tested locally and seems to be ok

**Comment by thepetk** [comment]
> Had to rebase and force-push the branch to meet the requirement of having the branch up to date before merging. @thepetk Feel free to re-lgtm if it looks okay with you.

@rm3l I've tested once again, seems to be ok :)

**Comment by rm3l** [comment]
> > Had to rebase and force-push the branch to meet the requirement of having the branch up to date before merging. @thepetk Feel free to re-lgtm if it looks okay with you.
> 
> @rm3l I've tested once again, seems to be ok :)

Thanks!

@michael-valdron Does that look good to you as well?

**Review by michael-valdron — COMMENTED** [review]
Looks good! Only change I would say we should do before we merge is to remove the deprecated `layout` from the `Image` components here:

1. https://github.com/rm3l/devfile-web/blob/340cff65cc2d7612e4e1b56029b5015a7aa27523/libs/core/src/components/hero/hero.tsx#L71
2. https://github.com/rm3l/devfile-web/blob/340cff65cc2d7612e4e1b56029b5015a7aa27523/libs/core/src/components/hero/hero.tsx#L112
3. https://github.com/rm3l/devfile-web/blob/340cff65cc2d7612e4e1b56029b5015a7aa27523/libs/core/src/components/hero/hero.tsx#L123

Removing these gets rid of the warning messages in the console. Testing the removals on my end this doesn't change anything on the landing page so the removals should be enough.

More information can be found here: https://nextjs.org/docs/messages/next-image-upgrade-to-13

**Comment by rm3l** [comment]
> Looks good! Only change I would say we should do before we merge is to remove the deprecated `layout` from the `Image` components here:
> 
> 1. [rm3l/devfile-web@`340cff6`/libs/core/src/components/hero/hero.tsx#L71](https://github.com/rm3l/devfile-web/blob/340cff65cc2d7612e4e1b56029b5015a7aa27523/libs/core/src/components/hero/hero.tsx#L71)
> 2. [rm3l/devfile-web@`340cff6`/libs/core/src/components/hero/hero.tsx#L112](https://github.com/rm3l/devfile-web/blob/340cff65cc2d7612e4e1b56029b5015a7aa27523/libs/core/src/components/hero/hero.tsx#L112)
> 3. [rm3l/devfile-web@`340cff6`/libs/core/src/components/hero/hero.tsx#L123](https://github.com/rm3l/devfile-web/blob/340cff65cc2d7612e4e1b56029b5015a7aa27523/libs/core/src/components/hero/hero.tsx#L123)
> 
> Removing these gets rid of the warning messages in the console. Testing the removals on my end this doesn't change anything on the landing page so the removals should be enough.
> 
> More information can be found here: [nextjs.org/docs/messages/next-image-upgrade-to-13](https://nextjs.org/docs/messages/next-image-upgrade-to-13)

Thanks. I'll apply your suggestions, but just curious, how did you get those warnings? I couldn't see them when building or serving the project.. I could only see my IDE mark that `layout` field as deprecated when explicitly opening `hero.tsx` (same behavior on the `main` branch).

**Comment by michael-valdron** [comment]
> > Looks good! Only change I would say we should do before we merge is to remove the deprecated `layout` from the `Image` components here:
> > 
> > 1. [rm3l/devfile-web@`340cff6`/libs/core/src/components/hero/hero.tsx#L71](https://github.com/rm3l/devfile-web/blob/340cff65cc2d7612e4e1b56029b5015a7aa27523/libs/core/src/components/hero/hero.tsx#L71)
> > 2. [rm3l/devfile-web@`340cff6`/libs/core/src/components/hero/hero.tsx#L112](https://github.com/rm3l/devfile-web/blob/340cff65cc2d7612e4e1b56029b5015a7aa27523/libs/core/src/components/hero/hero.tsx#L112)
> > 3. [rm3l/devfile-web@`340cff6`/libs/core/src/components/hero/hero.tsx#L123](https://github.com/rm3l/devfile-web/blob/340cff65cc2d7612e4e1b56029b5015a7aa27523/libs/core/src/components/hero/hero.tsx#L123)
> > 
> > Removing these gets rid of the warning messages in the console. Testing the removals on my end this doesn't change anything on the landing page so the removals should be enough.
> > More information can be found here: [nextjs.org/docs/messages/next-image-upgrade-to-13](https://nextjs.org/docs/messages/next-image-upgrade-to-13)
> 
> Thanks. I'll apply your suggestions, but just curious, how did you get those warnings? I couldn't see them when building or serving the project.. I could only see my IDE mark that `layout` field as deprecated when explicitly opening `hero.tsx` (same behavior on the `main` branch).

For me they only show up if you load the index of the landing page under development mode where `hero.tsx` is being rendered. They should be showing up under the process console and the web browser console.

Should see these warnings after page load:
```
Image with src "/_next/static/media/blur-cyan.d28a5585.png" has legacy prop "layout". Did you forget to run the codemod?
Read more: https://nextjs.org/docs/messages/next-image-upgrade-to-13
Image with src "/_next/static/media/blur-indigo.b752cf77.png" has legacy prop "layout". Did you forget to run the codemod?
Read more: https://nextjs.org/docs/messages/next-image-upgrade-to-13
```

**Review by michael-valdron — APPROVED** [review]
/lgtm

**Pull request merged**
